/*
 * gpio_user.c
 *
 *  Created on: Sep 11, 2025
 *      Author: oscar
 */

#include "gpio_user.h"

void gpio_init(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	GPIOC->MODER &= ~GPIO_MODER_MODER13;
	GPIOC->MODER |= GPIO_MODER_MODER13_0;
	GPIOC->MODER &= ~GPIO_MODER_MODER13_1;
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT13;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_0;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_1;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPDR13_0;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPDR13_1;
}
